### ISSUE TITLE
ProGuard rules

### ISSUE THREAD

**Issue by next-miguelangelbotija** [googlemaps/android-places-demos#20]
I try to add places library to my `InstantApp` and it works fine. The problem is that the library code is already obfuscated, and the library adds the next ProGuard rules:
```
# Proguard file to be exported as to proguard.txt in the 3P AAR release.
# The Places Library has already been obfuscated. This prevent further obfuscation.
-keep class com.google.android.libraries.places. ** {
    <fields>;
    <methods>;
}
```
For this reason I can disable this rule to allow ProGuard shrinks the code. The result of that is that library code size is about 326.8KB, whereas my application code is 213KB (or 363KB from all android code).

Is there any option to shrink the library code?
Do I need to open an issue into `issuetracker` of the library?

Thank you very much in advance!

**Comment by wangela** [comment]
Hi @next-miguelangelbotija, it would be great if you could open an issue in [issuetracker](https://developers.google.com/places/android-sdk/support#issue-tracker) since other developers of Instant Apps will likely want to shrink the size as well. You might want to make it a feature request that the library have a build version for apps that only use the API programmatically (no widgets). Eliminating widgets could greatly reduce the size needed for the library.
