### ISSUE TITLE
Place picker not working 

### ISSUE THREAD

**Issue by minichip17** [googlemaps/android-places-demos#35]
I have enabled billing in for my project , and enabled the place API and MAP SDK for android . Still my Place picker closes immediately when it opens .I have read about the deprecated methods and also seen your example that too have deprecated method. Can you please suggest some solution to overcome this issue .

**Comment by wangela** [comment]
Place picker has been [deprecated since January 29](https://developers.google.com/maps/deprecations#places_sdks_for_android_and_ios_-). To learn how to build similar functionality, see the [codelab for Current Place](https://codelabs.developers.google.com/codelabs/location-places-android/index.html?index=..%2F..index#0).
